/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ApiMotorCommandRouteImport } from './routes/api/motor-command'
import { Route as ApiNotificationRouteImport } from './routes/api/notification'
import { Route as ApiNotificationAcknowledgeRouteImport } from './routes/api/notification-acknowledge'
import { Route as ApiNotificationHistoryRouteImport } from './routes/api/notification-history'
import { Route as ApiNotificationReleaseRouteImport } from './routes/api/notification-release'
import { Route as ApiReleaseCompleteRouteImport } from './routes/api/release-complete'
import { Route as ApiSensorReadingRouteImport } from './routes/api/sensor-reading'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMotorCommandRoute = ApiMotorCommandRouteImport.update({
  id: '/api/motor-command',
  path: '/api/motor-command',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationRoute = ApiNotificationRouteImport.update({
  id: '/api/notification',
  path: '/api/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationAcknowledgeRoute =
  ApiNotificationAcknowledgeRouteImport.update({
    id: '/api/notification-acknowledge',
    path: '/api/notification-acknowledge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotificationHistoryRoute = ApiNotificationHistoryRouteImport.update({
  id: '/api/notification-history',
  path: '/api/notification-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationReleaseRoute = ApiNotificationReleaseRouteImport.update({
  id: '/api/notification-release',
  path: '/api/notification-release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleaseCompleteRoute = ApiReleaseCompleteRouteImport.update({
  id: '/api/release-complete',
  path: '/api/release-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSensorReadingRoute = ApiSensorReadingRouteImport.update({
  id: '/api/sensor-reading',
  path: '/api/sensor-reading',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/api/motor-command': typeof ApiMotorCommandRoute
  '/api/notification': typeof ApiNotificationRoute
  '/api/notification-acknowledge': typeof ApiNotificationAcknowledgeRoute
  '/api/notification-history': typeof ApiNotificationHistoryRoute
  '/api/notification-release': typeof ApiNotificationReleaseRoute
  '/api/release-complete': typeof ApiReleaseCompleteRoute
  '/api/sensor-reading': typeof ApiSensorReadingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/api/motor-command': typeof ApiMotorCommandRoute
  '/api/notification': typeof ApiNotificationRoute
  '/api/notification-acknowledge': typeof ApiNotificationAcknowledgeRoute
  '/api/notification-history': typeof ApiNotificationHistoryRoute
  '/api/notification-release': typeof ApiNotificationReleaseRoute
  '/api/release-complete': typeof ApiReleaseCompleteRoute
  '/api/sensor-reading': typeof ApiSensorReadingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/api/motor-command': typeof ApiMotorCommandRoute
  '/api/notification': typeof ApiNotificationRoute
  '/api/notification-acknowledge': typeof ApiNotificationAcknowledgeRoute
  '/api/notification-history': typeof ApiNotificationHistoryRoute
  '/api/notification-release': typeof ApiNotificationReleaseRoute
  '/api/release-complete': typeof ApiReleaseCompleteRoute
  '/api/sensor-reading': typeof ApiSensorReadingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/api/motor-command'
    | '/api/notification'
    | '/api/notification-acknowledge'
    | '/api/notification-history'
    | '/api/notification-release'
    | '/api/release-complete'
    | '/api/sensor-reading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/api/motor-command'
    | '/api/notification'
    | '/api/notification-acknowledge'
    | '/api/notification-history'
    | '/api/notification-release'
    | '/api/release-complete'
    | '/api/sensor-reading'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/faq'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/api/motor-command'
    | '/api/notification'
    | '/api/notification-acknowledge'
    | '/api/notification-history'
    | '/api/notification-release'
    | '/api/release-complete'
    | '/api/sensor-reading'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ApiMotorCommandRoute: typeof ApiMotorCommandRoute
  ApiNotificationRoute: typeof ApiNotificationRoute
  ApiNotificationAcknowledgeRoute: typeof ApiNotificationAcknowledgeRoute
  ApiNotificationHistoryRoute: typeof ApiNotificationHistoryRoute
  ApiNotificationReleaseRoute: typeof ApiNotificationReleaseRoute
  ApiReleaseCompleteRoute: typeof ApiReleaseCompleteRoute
  ApiSensorReadingRoute: typeof ApiSensorReadingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/motor-command': {
      id: '/api/motor-command'
      path: '/api/motor-command'
      fullPath: '/api/motor-command'
      preLoaderRoute: typeof ApiMotorCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notification': {
      id: '/api/notification'
      path: '/api/notification'
      fullPath: '/api/notification'
      preLoaderRoute: typeof ApiNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notification-acknowledge': {
      id: '/api/notification-acknowledge'
      path: '/api/notification-acknowledge'
      fullPath: '/api/notification-acknowledge'
      preLoaderRoute: typeof ApiNotificationAcknowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notification-history': {
      id: '/api/notification-history'
      path: '/api/notification-history'
      fullPath: '/api/notification-history'
      preLoaderRoute: typeof ApiNotificationHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notification-release': {
      id: '/api/notification-release'
      path: '/api/notification-release'
      fullPath: '/api/notification-release'
      preLoaderRoute: typeof ApiNotificationReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/release-complete': {
      id: '/api/release-complete'
      path: '/api/release-complete'
      fullPath: '/api/release-complete'
      preLoaderRoute: typeof ApiReleaseCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sensor-reading': {
      id: '/api/sensor-reading'
      path: '/api/sensor-reading'
      fullPath: '/api/sensor-reading'
      preLoaderRoute: typeof ApiSensorReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ApiMotorCommandRoute: ApiMotorCommandRoute,
  ApiNotificationRoute: ApiNotificationRoute,
  ApiNotificationAcknowledgeRoute: ApiNotificationAcknowledgeRoute,
  ApiNotificationHistoryRoute: ApiNotificationHistoryRoute,
  ApiNotificationReleaseRoute: ApiNotificationReleaseRoute,
  ApiReleaseCompleteRoute: ApiReleaseCompleteRoute,
  ApiSensorReadingRoute: ApiSensorReadingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
